### ISSUE TITLE
Need help with frontend?

### ISSUE THREAD

**Issue by knakamura13** [Mihaiii/token_forge#1]
Found your project idea on reddit. I know you haven't really started yet, but I'm curious what help you might need on the frontend. I'm interested because the idea (click on any LLM-generated token to regenerate from that point) is really fascinating and feels like something that would be fun to use.

**Comment by Mihaiii** [comment]
Hey!

Thank you very much for wanting to help out!

I just stumbled upon another post from 2 hours ago that implemented exactly what I wanted to implement. Check it out!

https://www.reddit.com/r/LocalLLaMA/s/WyhTjCxBAv

Therefore, I won't work on the exact same solution.
Closing as I'll either abandon this repo or delete it.
